# Tema 1 - Matrices
Vamos a ver como crear una matriz utizando la librería `numpy`

In [1]:
row = [1,2,3]
row

[1, 2, 3]

In [3]:
col = [[1], [2], [3]]
col

[[1], [2], [3]]

In [5]:
M = [[1,2,3],[4,5,6],[7,8,9]]
M

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
M[1][1]

5

In [7]:
M[0]

[1, 2, 3]

In [8]:
import numpy as np

In [14]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = float)

In [32]:
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [33]:
M[0]

array([1., 2., 3.])

In [34]:
for row in M: #columna
    print(row[0])

1.0
4.0
7.0


np.zeros((2,3))

In [17]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.shape(M)

(3, 3)

In [21]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,0],[1,-1]])

In [22]:
A+B #suma de matrices

array([[4, 2],
       [4, 3]])

In [23]:
A.dot(B) #Multiplicación de matrices

array([[ 5, -2],
       [13, -4]])

In [24]:
print(A.dot(B))

[[ 5 -2]
 [13 -4]]


In [25]:
A.transpose() # Transpuesta

array([[1, 3],
       [2, 4]])

In [26]:
A.trace() # Traza de la matriz suma de diagonal

5

In [27]:
np.linalg.matrix_rank(A) #rango de la matriz

2

In [28]:
np.linalg.matrix_power(A,5)

array([[1069, 1558],
       [2337, 3406]])

In [29]:
np.linalg.det(A) # Determinante de A

-2.0000000000000004

In [31]:
np.linalg.inv(A).dot(A) #Matriz identidad

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

**No se nos ocurrirá hacer la inversa de una matriz cuadrada, ni de una matriz cuyo rango sea inferior a su rango**