# NumPy

Ofrece muchas opciones para crear arrays

In [2]:
import numpy as np

In [3]:
L1 =[1,2,3,4,5,6,7,8] #Crear una lista

In [4]:
x1 = np.array(L1)
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
x2 = np.array(L1, dtype = 'float32')
x2

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

### Tipo de datos:
- bool_
- int_, intc (entero de c), intp (entero para indexar), int8 (8 bits), int16, int32, int64
- uint8 (8 bits), uint16, uint32, uint64 *enteros sin signo*
- float_ (float64), float16, float32, float64(double)
- complex_ (complex64), complex64, complex128 (a+bi, a, b $\in$ float)


In [7]:
np.zeros((3,4)) # Matrices de 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((4,3)) # Matrices de 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.arange(10) # valores entre 0 incluido y 10 exluido

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3,13, dtype = np.float) # valores flotantes entre 3 incluido y 13 excluido

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [11]:
np.arange(4,5,0.1) # valores entre 4 incluido y 5 excluido, saltandose valores entre 0.1

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [12]:
np.linspace(1.,7.,12) # 12 números entre 1 y 7 


array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [14]:
np.eye(5) # Matriz identidad de 5x5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
x.reshape((6,4)) # reordena la lista x como matriz 6x4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
x.reshape((3,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [26]:
x = np.array([[1,2,3,4], [5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
np.ravel(x) # Devuelve el array aplanado y lo deja así

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
x.flatten() # muestra el vector aplanado, mas no lo modifica

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
np.transpose(x) #trasponer matrices

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [30]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
np.resize(x, (5,3)) # genera matrix 5x3 y las que quedan vacías las comienza a rellenar con la misma

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

### Ejercicios
1. Crear un array de datos con valores entre 5 y 120

In [32]:
np.arange(5,121)

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120])

2. Crear una matrix 4x4 con los valores desde 0 hasta 5


In [34]:
a = np.arange(16)
np.reshape(a,(4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

3. Crear la identidad 7x7 

In [35]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

4. Crear un array de 20 elementos y transformarlo en matrix 5x4

In [36]:
m = np.arange(20)
np.reshape(m, (5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

5. Crear un array con 20 números con los valores entre 0 y 5 espaciados de forma uniforme


In [37]:
np.linspace(0.,5.,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

# Propiedades de arrays

In [41]:
x =np.arange(12)
x = x.reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
x.ndim # dimensiones de la matriz

2

In [43]:
x.shape # La forma de la matriz

(3, 4)

In [44]:
x.size # Numero total de elementos de la matriz

12

In [45]:
x.dtype #tipo de dato de la matriz

dtype('int32')

In [46]:
x.itemsize # Cuantos bytes de informacion se ocuparan por lemento

4

In [47]:
x.data # La memoria para almacenar el array.

In [48]:
x[2]

array([ 8,  9, 10, 11])

In [49]:
x[2,1]

9

In [51]:
x.shape = (4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
x[1:3, 0:2] # Extrae fila de la 1 a la 3 (sin incluir) y columna de la 0 a la 2 (sin incluir)

array([[3, 4],
       [6, 7]])

In [54]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
y[1:7:2]  # cuenta numeros entre 1 y 7 (excluido) de dos en dos 

array([1, 3, 5])

In [56]:
z = np.arange(10, 6, -1)
z

array([10,  9,  8,  7])

In [57]:
y[z]

array([10,  9,  8,  7])

In [58]:
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [59]:
x[x>30] # Numeros mayores que 30

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [60]:
cond = (x<25)
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [61]:
x[cond]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [62]:
x[12:24] = 1
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [64]:
x[13:16] =[6,9,12] # cambia numeros
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [66]:
x.dtype

dtype('int32')

In [69]:
x[5] = 3.1415 # como el tipo de dato es entero, si ingresamos un float lo redondea
x

array([ 0,  1,  2,  3,  4,  3,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

## Copias y vistas de arrays

In [71]:
x = np.arange(10)

In [72]:
y = x # No crea una copia de array

In [74]:
y.shape = (2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [75]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [76]:
z = x.copy()
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [77]:
z is x # z es una copia de x

False

In [78]:
y is x

True

In [79]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [81]:
t = x.view()  #Genera una vista de x
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
t.shape = (5,2) # Cambia la vista del objeto pero no al objeto
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [84]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
s = x[0:2, 1:3] # Seleccionar la parte de un array es una vista
s

array([[1, 2],
       [6, 7]])

In [89]:
s[:]= 5
s

array([[5, 5],
       [5, 5]])

In [90]:
x

array([[0, 5, 5, 3, 4],
       [5, 5, 5, 8, 9]])

In [91]:
y

array([[0, 5, 5, 3, 4],
       [5, 5, 5, 8, 9]])

In [92]:
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Funciones Universales (ufunc)

Funciones que se aplican en todo el array sin tener 
- Unarias: sqrt, sin, con, **2
- Binarias (reciben dos array y devuelven uno): maximum, minimum, 

In [94]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
x+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [96]:
x-3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [97]:
x/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [98]:
alpha = np.linspace(0,2*np.pi, 4)
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [99]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [101]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [102]:
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

In [103]:
np.exp(x) # e^x

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [104]:
np.exp(x) #2^x

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [105]:
np.power(3,x)

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683], dtype=int32)

$$\sum_{i=1}^n x_i$$

In [106]:
np.power(x,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [108]:
np.nansum(x) # suma borrando los valores na

45

In [109]:
np.prod(x) #producto de elemento

0

In [110]:
np.mean(x) # media

4.5

In [111]:
np.median(x)

4.5

In [113]:
np.min(x)

0

In [114]:
np.max(x)

9

In [115]:
np.std(x)

2.8722813232690143

In [116]:
np.var(x)

8.25

In [117]:
np.argmin(x) #posicion donde está el numero mas pequeño

0

In [118]:
np.argmax(x) #posición del número más grande

9

In [119]:
np.percentile(x, q=0.5) # percentiles

0.045

In [121]:
y = np.array([True, True, True, True])

In [122]:
np.any(y) # Si alguno es True

True

In [123]:
np.all(y) # Si todos son True

True

In [128]:
np.random.seed(2019)
z = np.random.random((3,5)) # Valores aleatorios
z

array([[0.90348221, 0.39308051, 0.62396996, 0.6378774 , 0.88049907],
       [0.29917202, 0.70219827, 0.90320616, 0.88138193, 0.4057498 ],
       [0.45244662, 0.26707032, 0.16286487, 0.8892147 , 0.14847623]])

In [129]:
z.sum() #suma de todos los valores

8.550690063213514

In [126]:
z.sum(axis=0) #suma por columnas

array([1.46217212, 1.58512104, 1.65162221, 1.32960227, 1.3177242 ])

In [127]:
z.sum(axis=1) #suma por filas

array([1.92075848, 2.81403368, 2.61144969])